### ISSUE TITLE
Не устанавливается через npm

### ISSUE THREAD

**Issue by egorvinogradov** [tamtam-chat/lottie-player#2]
Создал .npmrc с содержимым:
`@tamtam-chat:registry=https://npm.pkg.github.com`

При запуске `npm install @tamtam-chat/lottie-player` выдает:
```
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/@tamtam-chat%2flottie-player - authentication token not provided
```

**Comment by sergeche** [comment]
Попробуйте сейчас, должно ставиться

**Comment by egorvinogradov** [comment]
Спасибо за ответ, но, к сожалению, не работает — ошибка та же. Аналогично, по ссылке https://npm.pkg.github.com/@tamtam-chat/lottie-player открывается ответ `{"error": "authentication token not provided"}`

Нет ли планов выложить это в https://npmjs.com?

**Comment by sergeche** [comment]
Я поменял права на доступ (был приватный, стал публичный) и проверил на новом npm-проекте: всё установилось без проблем. Возможно, проблемы в кэше npm, можно попробовать его сбросить.

Насчёт реестра npm: может быть потом попробую, но хотело бы тут всё хранить

**Comment by egorvinogradov** [comment]
Нашел решение, помог [Reddit](https://www.reddit.com/r/node/comments/105bexo/installing_package_with_dependency_from_github/) и [StackOverflow](https://stackoverflow.com/questions/72412063/personal-access-tokens-for-install-github-npm-packages).

В `.npmrc` нужно добавить также токен с Гитхаба.

Переписал кусок документации и сделал [pull request](https://github.com/tamtam-chat/lottie-player/pull/3) -- в нем подробнее.

Актуальным остается вопрос выкладки в npm -- так как сейчас всем желающим установить придется проделывать эти манипуляции с созданием Github-токена, в том числе всем членам команды любого проекта, где установлен lottie-player.

**Comment by sergeche** [comment]
Насколько я понял из документации, токен нужен для чтения из приватного пакета.
Пример как я на чистом репозитории поставил модуль

<img width="807" alt="image" src="https://user-images.githubusercontent.com/93595/224003092-330b0471-28f3-4d20-b73a-a713b4fc9f4a.png">

**Comment by sergeche** [comment]
У меня там действительно потом сам проставился токен в `.npmrc`.

ОК, попробую что-нибудь придумать с выкладкой в npm

**Comment by egorvinogradov** [comment]
Спасибо!

**Comment by sergeche** [comment]
Пакет теперь публикуется и ставится из основного npm. В README обновил инструкцию
